openapi: 3.0.0
info:
  version: 2012-10-25
  x-release: v4
  title: 'AWS Direct Connect #X Amz Target=OvertureService.AcceptDirectConnectGatewayAssociationProposal #X Amz Target=OvertureService.AcceptDirectConnectGatewayAssociationProposal #X Amz Target=OvertureService.AcceptDirectConnectGatewayAssociationProposal API'
  description: Direct Connect links your internal network to an Direct Connect location over a standard Ethernet fiber-optic cable. One end of the cable is connected to your router, the other to an Direct Connect router. With this connection in place, you can create virtual interfaces directly to the Amazon Web Services Cloud (for example, to Amazon EC2 and Amazon S3) and to Amazon VPC, bypassing Internet service providers in your network path. A connection provides access to all Amazon Web Services Regions except the China (Beijing) and (China) Ningxia Regions. Amazon Web Services resources in the China Regions can only be accessed through locations associated with those Regions.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: directconnect
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/directconnect-2012-10-25.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://directconnect.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Direct Connect multi-region endpoint
- url: https://directconnect.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Direct Connect multi-region endpoint
- url: http://directconnect.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Direct Connect endpoint for China (Beijing) and China (Ningxia)
- url: https://directconnect.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Direct Connect endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=OvertureService.AcceptDirectConnectGatewayAssociationProposal'
paths:
  /#X-Amz-Target=OvertureService.AcceptDirectConnectGatewayAssociationProposal:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: AcceptDirectConnectGatewayAssociationProposal
      description: Accepts a proposal request to attach a virtual private gateway or transit gateway to a Direct Connect gateway.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptDirectConnectGatewayAssociationProposalResult'
        '480':
          description: DirectConnectServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectConnectServerException'
        '481':
          description: DirectConnectClientException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectConnectClientException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptDirectConnectGatewayAssociationProposalRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - OvertureService.AcceptDirectConnectGatewayAssociationProposal
      tags:
      - '#X Amz Target=OvertureService.AcceptDirectConnectGatewayAssociationProposal'
components:
  schemas:
    StateChangeError:
      type: string
    DirectConnectServerException: {}
    AcceptDirectConnectGatewayAssociationProposalResult:
      type: object
      properties:
        directConnectGatewayAssociation:
          $ref: '#/components/schemas/DirectConnectGatewayAssociation'
    DirectConnectGatewayAssociationProposalId:
      type: string
    DirectConnectGatewayAssociationId:
      type: string
    CIDR:
      type: string
    VirtualGatewayRegion:
      type: string
      deprecated: true
    RouteFilterPrefix:
      type: object
      properties:
        cidr:
          allOf:
          - $ref: '#/components/schemas/CIDR'
          - description: The CIDR block for the advertised route. Separate multiple routes using commas. An IPv6 CIDR must use /64 or shorter.
      description: Information about a route filter prefix that a customer can advertise through Border Gateway Protocol (BGP) over a public virtual interface.
    RouteFilterPrefixList:
      type: array
      items:
        $ref: '#/components/schemas/RouteFilterPrefix'
    DirectConnectGatewayAssociation:
      type: object
      properties:
        directConnectGatewayId:
          allOf:
          - $ref: '#/components/schemas/DirectConnectGatewayId'
          - description: The ID of the Direct Connect gateway.
        directConnectGatewayOwnerAccount:
          allOf:
          - $ref: '#/components/schemas/OwnerAccount'
          - description: The ID of the Amazon Web Services account that owns the associated gateway.
        associationState:
          allOf:
          - $ref: '#/components/schemas/DirectConnectGatewayAssociationState'
          - description: '<p>The state of the association. The following are the possible values:</p> <ul> <li> <p> <code>associating</code>: The initial state after calling <a>CreateDirectConnectGatewayAssociation</a>.</p> </li> <li> <p> <code>associated</code>: The Direct Connect gateway and virtual private gateway or transit gateway are successfully associated and ready to pass traffic.</p> </li> <li> <p> <code>disassociating</code>: The initial state after calling <a>DeleteDirectConnectGatewayAssociation</a>.</p> </li> <li> <p> <code>disassociated</code>: The virtual private gateway or transit gateway is disassociated from the Direct Connect gateway. Traffic flow between the Direct Connect gateway and virtual private gateway or transit gateway is stopped.</p> </li> <li> <p> <code>updating</code>: The CIDR blocks for the virtual private gateway or transit gateway are currently being updated. This could be new CIDR blocks added or current CIDR blocks removed.</p> </li> </ul>'
        stateChangeError:
          allOf:
          - $ref: '#/components/schemas/StateChangeError'
          - description: The error message if the state of an object failed to advance.
        associatedGateway:
          allOf:
          - $ref: '#/components/schemas/AssociatedGateway'
          - description: Information about the associated gateway.
        associationId:
          allOf:
          - $ref: '#/components/schemas/DirectConnectGatewayAssociationId'
          - description: The ID of the Direct Connect gateway association.
        allowedPrefixesToDirectConnectGateway:
          allOf:
          - $ref: '#/components/schemas/RouteFilterPrefixList'
          - description: The Amazon VPC prefixes to advertise to the Direct Connect gateway.
        virtualGatewayId:
          allOf:
          - $ref: '#/components/schemas/VirtualGatewayId'
          - description: The ID of the virtual private gateway. Applies only to private virtual interfaces.
        virtualGatewayRegion:
          allOf:
          - $ref: '#/components/schemas/VirtualGatewayRegion'
          - description: The Amazon Web Services Region where the virtual private gateway is located.
        virtualGatewayOwnerAccount:
          allOf:
          - $ref: '#/components/schemas/OwnerAccount'
          - description: The ID of the Amazon Web Services account that owns the virtual private gateway.
      description: Information about an association between a Direct Connect gateway and a virtual private gateway or transit gateway.
    GatewayIdentifier:
      type: string
    GatewayType:
      type: string
      enum:
      - virtualPrivateGateway
      - transitGateway
    OwnerAccount:
      type: string
    AssociatedGateway:
      type: object
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/GatewayIdentifier'
          - description: The ID of the associated gateway.
        type:
          allOf:
          - $ref: '#/components/schemas/GatewayType'
          - description: The type of associated gateway.
        ownerAccount:
          allOf:
          - $ref: '#/components/schemas/OwnerAccount'
          - description: The ID of the Amazon Web Services account that owns the associated virtual private gateway or transit gateway.
        region:
          allOf:
          - $ref: '#/components/schemas/Region'
          - description: The Region where the associated gateway is located.
      description: Information about the associated gateway.
    AcceptDirectConnectGatewayAssociationProposalRequest:
      type: object
      required:
      - directConnectGatewayId
      - proposalId
      - associatedGatewayOwnerAccount
      title: AcceptDirectConnectGatewayAssociationProposalRequest
      properties:
        directConnectGatewayId:
          allOf:
          - $ref: '#/components/schemas/DirectConnectGatewayId'
          - description: The ID of the Direct Connect gateway.
        proposalId:
          allOf:
          - $ref: '#/components/schemas/DirectConnectGatewayAssociationProposalId'
          - description: The ID of the request proposal.
        associatedGatewayOwnerAccount:
          allOf:
          - $ref: '#/components/schemas/OwnerAccount'
          - description: The ID of the Amazon Web Services account that owns the virtual private gateway or transit gateway.
        overrideAllowedPrefixesToDirectConnectGateway:
          allOf:
          - $ref: '#/components/schemas/RouteFilterPrefixList'
          - description: <p>Overrides the Amazon VPC prefixes advertised to the Direct Connect gateway.</p> <p>For information about how to set the prefixes, see <a href="https://docs.aws.amazon.com/directconnect/latest/UserGuide/multi-account-associate-vgw.html#allowed-prefixes">Allowed Prefixes</a> in the <i>Direct Connect User Guide</i>.</p>
    Region:
      type: string
    DirectConnectGatewayId:
      type: string
    DirectConnectClientException: {}
    DirectConnectGatewayAssociationState:
      type: string
      enum:
      - associating
      - associated
      - disassociating
      - disassociated
      - updating
    VirtualGatewayId:
      type: string
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/directconnect/
x-hasEquivalentPaths: true
