openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'AWS Direct Connect #X Amz Target=OvertureService.AcceptDirectConnectGatewayAssociationProposal #X Amz Target=OvertureService.AcceptDirectConnectGatewayAssociationProposal #X Amz Target=OvertureService.DescribeRouterConfiguration #X Amz Target=OvertureService.DescribeRouterConfiguration #X Amz Target=OvertureService.DescribeRouterConfiguration API'
  description: Direct Connect links your internal network to an Direct Connect location over a standard Ethernet fiber-optic cable. One end of the cable is connected to your router, the other to an Direct Connect router. With this connection in place, you can create virtual interfaces directly to the Amazon Web Services Cloud (for example, to Amazon EC2 and Amazon S3) and to Amazon VPC, bypassing Internet service providers in your network path. A connection provides access to all Amazon Web Services Regions except the China (Beijing) and (China) Ningxia Regions. Amazon Web Services resources in the China Regions can only be accessed through locations associated with those Regions.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: directconnect
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/directconnect-2012-10-25.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://directconnect.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Direct Connect multi-region endpoint
- url: https://directconnect.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Direct Connect multi-region endpoint
- url: http://directconnect.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Direct Connect endpoint for China (Beijing) and China (Ningxia)
- url: https://directconnect.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Direct Connect endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=OvertureService.DescribeRouterConfiguration'
paths:
  /#X-Amz-Target=OvertureService.DescribeRouterConfiguration:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeRouterConfiguration
      description: ' Details about the router. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeRouterConfigurationResponse'
        '480':
          description: DirectConnectServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectConnectServerException'
        '481':
          description: DirectConnectClientException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectConnectClientException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DescribeRouterConfigurationRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - OvertureService.DescribeRouterConfiguration
      tags:
      - '#X Amz Target=OvertureService.DescribeRouterConfiguration'
components:
  schemas:
    RouterType:
      type: object
      properties:
        vendor:
          allOf:
          - $ref: '#/components/schemas/Vendor'
          - description: The vendor for the virtual interface's router.
        platform:
          allOf:
          - $ref: '#/components/schemas/Platform'
          - description: The virtual interface router platform.
        software:
          allOf:
          - $ref: '#/components/schemas/Software'
          - description: 'The router software. '
        xsltTemplateName:
          allOf:
          - $ref: '#/components/schemas/XsltTemplateName'
          - description: The template for the virtual interface's router.
        xsltTemplateNameForMacSec:
          allOf:
          - $ref: '#/components/schemas/XsltTemplateNameForMacSec'
          - description: The MAC Security (MACsec) template for the virtual interface's router.
        routerTypeIdentifier:
          allOf:
          - $ref: '#/components/schemas/RouterTypeIdentifier'
          - description: Identifies the router by a combination of vendor, platform, and software version. For example, <code>CiscoSystemsInc-2900SeriesRouters-IOS124</code>.
      description: Information about the virtual router.
    VirtualInterfaceId:
      type: string
    XsltTemplateName:
      type: string
    DirectConnectClientException: {}
    XsltTemplateNameForMacSec:
      type: string
    Platform:
      type: string
    DirectConnectServerException: {}
    DescribeRouterConfigurationRequest:
      type: object
      required:
      - virtualInterfaceId
      title: DescribeRouterConfigurationRequest
      properties:
        virtualInterfaceId:
          allOf:
          - $ref: '#/components/schemas/VirtualInterfaceId'
          - description: The ID of the virtual interface.
        routerTypeIdentifier:
          allOf:
          - $ref: '#/components/schemas/RouterTypeIdentifier'
          - description: Identifies the router by a combination of vendor, platform, and software version. For example, <code>CiscoSystemsInc-2900SeriesRouters-IOS124</code>.
      description: Provides the details about a virtual interface's router.
    RouterTypeIdentifier:
      type: string
    RouterConfig:
      type: string
    Software:
      type: string
    Vendor:
      type: string
    VirtualInterfaceName:
      type: string
    DescribeRouterConfigurationResponse:
      type: object
      properties:
        customerRouterConfig:
          allOf:
          - $ref: '#/components/schemas/RouterConfig'
          - description: The customer router configuration.
        router:
          allOf:
          - $ref: '#/components/schemas/RouterType'
          - description: The details about the router.
        virtualInterfaceId:
          allOf:
          - $ref: '#/components/schemas/VirtualInterfaceId'
          - description: The ID assigned to the virtual interface.
        virtualInterfaceName:
          allOf:
          - $ref: '#/components/schemas/VirtualInterfaceName'
          - description: Provides the details about a virtual interface's router.
  parameters:
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/directconnect/
x-hasEquivalentPaths: true
